### ISSUE TITLE
2D Rendering

### ISSUE THREAD

**Issue by Ace8Underscore** [GishReloaded/Gish-Code-1.12.2#5]
Im currently trying to add my armor hud hack which draws the armor inventory and the durability bar above the hunger bar. I know this code works because ive gotten it to work on another base i use to use. Any ideas? when turning on the hack i get this errors spammed in chat 
RuntimeException: onRenderGameOverlay
java.lang.NullPointerException

**Comment by GishReloaded** [comment]
Please send me full exception

**Comment by Ace8Underscore** [comment]
here were the lines i got in colsol
[20:11:42] [main/INFO]: [CHAT] §8AceHack§7 §8[§4ERROR§8]§c RuntimeException: onRenderGameOverlay
[20:11:42] [main/INFO]: [CHAT] §8AceHack§7 §8[§4ERROR§8]§c java.lang.NullPointerException
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: java.lang.NullPointerException
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at io.ace.acehack.hack.hacks.Render.ArmourHUD.onRenderGameOverlay(ArmourHUD.java:59)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at io.ace.acehack.managers.HackManager.onRenderGameOverlay(HackManager.java:298)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at io.ace.acehack.EventsHandler.onRenderGameOverlay(EventsHandler.java:191)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_14_EventsHandler_onRenderGameOverlay_Text.invoke(.dynamic)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:713)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:172)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1151)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1207)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at net.minecraft.client.Minecraft.run(Minecraft.java:441)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at net.minecraft.client.main.Main.main(Main.java:118)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
[20:11:42] [main/INFO] [STDERR]: [io.ace.acehack.EventsHandler:onRenderGameOverlay:193]: 	at GradleStart.main(GradleStart.java:25)

**Comment by Ace8Underscore** [comment]
idk ive been trying to mess with my problem and im still a bit confused. not trying to be a problem but just asking if this could help you understand what i mean. Here is the ArmourHUD.class @ https://pastebin.com/kXKZS5KB 
im just completely comfused on how this isnt rendering the item and instead giving me an error
if there is anyway we could get in contact my discord is Ace_#1233 if not its okay.

**Comment by GishReloaded** [comment]
Error in this code. This is a working version: https://ghostbin.co/paste/wpbek
